// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: lexer4.flex

package com.example.creadorform.interprete.parser;

import java_cup.runtime.Symbol;
import java.util.ArrayList;
import java.util.List;
import java.io.IOException;


@SuppressWarnings("fallthrough")
public class LexerPKM extends Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\24\u0200\1\u0300\11\u0200\1\u0400\1\u0500\16\u0200"+
    "\1\u0600\247\u0200\10\u0700\u1020\u0200";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\4\22\0\1\5\1\0"+
    "\1\6\1\7\4\0\1\10\1\11\2\0\1\12\1\13"+
    "\1\0\1\14\3\15\1\16\6\15\1\17\1\0\1\20"+
    "\1\21\1\22\1\0\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\33\1\34\1\0\1\35\1\36"+
    "\1\37\1\40\1\41\1\42\1\0\1\43\1\44\1\45"+
    "\1\46\1\47\1\50\1\51\1\52\1\53\1\54\1\55"+
    "\1\56\1\57\1\60\1\0\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\33\1\34\1\0\1\35\1\36"+
    "\1\37\1\40\1\41\1\42\1\0\1\43\1\44\1\45"+
    "\1\46\1\47\1\50\1\51\1\52\1\53\1\61\1\62"+
    "\1\63\7\0\1\3\32\0\1\64\217\0\2\34\115\0"+
    "\1\44\u0200\0\1\64\177\0\13\64\35\0\2\3\5\0"+
    "\1\64\57\0\1\64\312\0\1\35\325\0\1\64\377\0"+
    "\u0100\65";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[2048];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\1\3\1\1\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\21\1\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\17\1\23\42\0"+
    "\1\24\32\0\1\25\34\0\1\26\2\0\1\27\2\0"+
    "\1\30\1\31\1\0\1\32\4\0\1\33\2\0\1\34"+
    "\26\0\1\35\13\0\1\36\1\37\1\0\1\40\1\41"+
    "\7\0\1\42\1\43\1\23\3\0\1\44\1\45\3\0"+
    "\1\46\3\0\1\47\1\0\1\50\4\0\1\51\7\0"+
    "\1\52\1\0\1\53\1\0\1\54\4\0\1\55\1\56"+
    "\3\0\1\57\6\0\1\60\1\61\4\0\1\62\1\0"+
    "\1\63\7\0\1\64\6\0\1\65\1\66\1\0\1\67"+
    "\1\70\3\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[276];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\66\0\154\0\242\0\154\0\330\0\u010e\0\154"+
    "\0\154\0\154\0\154\0\u0144\0\u017a\0\154\0\154\0\u01b0"+
    "\0\u01e6\0\u021c\0\u0252\0\u0288\0\u02be\0\u02f4\0\u032a\0\u0360"+
    "\0\u0396\0\u03cc\0\u0402\0\u0438\0\u046e\0\u04a4\0\u04da\0\u0510"+
    "\0\154\0\154\0\u0546\0\154\0\154\0\u057c\0\u05b2\0\u05e8"+
    "\0\u061e\0\u0654\0\u010e\0\u068a\0\u017a\0\u06c0\0\u06f6\0\u072c"+
    "\0\u0762\0\u0798\0\u07ce\0\u0804\0\u083a\0\u0870\0\u08a6\0\u08dc"+
    "\0\u0912\0\u0948\0\u097e\0\u09b4\0\u09ea\0\u0a20\0\u0a56\0\u0a8c"+
    "\0\u0ac2\0\u0af8\0\u0b2e\0\u0b64\0\u0b9a\0\u0bd0\0\u0c06\0\u0c3c"+
    "\0\u0c72\0\u0ca8\0\154\0\u0cde\0\u0d14\0\u0d4a\0\u0d80\0\u0db6"+
    "\0\u0dec\0\u0e22\0\u0e58\0\u0e8e\0\u0ec4\0\u0efa\0\u0f30\0\u0f66"+
    "\0\u0f9c\0\u0fd2\0\u1008\0\u103e\0\u1074\0\u10aa\0\u10e0\0\u1116"+
    "\0\u114c\0\u1182\0\u11b8\0\u11ee\0\u1224\0\154\0\u125a\0\u1290"+
    "\0\u12c6\0\u12fc\0\u1332\0\u1368\0\u139e\0\u13d4\0\u140a\0\u1440"+
    "\0\u1476\0\u14ac\0\u14e2\0\u1518\0\u154e\0\u1584\0\u15ba\0\u15f0"+
    "\0\u1626\0\u165c\0\u1692\0\u16c8\0\u16fe\0\u1734\0\u176a\0\u17a0"+
    "\0\u17d6\0\u180c\0\154\0\u1842\0\u1878\0\154\0\u18ae\0\u18e4"+
    "\0\154\0\154\0\u191a\0\154\0\u1950\0\u1986\0\u19bc\0\u19f2"+
    "\0\154\0\u1a28\0\u1a5e\0\154\0\u1a94\0\u1aca\0\u1b00\0\u1b36"+
    "\0\u1b6c\0\u1ba2\0\u1bd8\0\u1c0e\0\u1c44\0\u1c7a\0\u1cb0\0\u1ce6"+
    "\0\u1d1c\0\u1d52\0\u1d88\0\u1dbe\0\u1df4\0\u1e2a\0\u1e60\0\u1e96"+
    "\0\u1ecc\0\u1f02\0\154\0\u1f38\0\u1f6e\0\u1fa4\0\u1fda\0\u2010"+
    "\0\u2046\0\u207c\0\u20b2\0\u20e8\0\u211e\0\u2154\0\154\0\154"+
    "\0\u218a\0\154\0\154\0\u21c0\0\u21f6\0\u222c\0\u2262\0\u2298"+
    "\0\u22ce\0\u2304\0\154\0\154\0\154\0\u233a\0\u2370\0\u23a6"+
    "\0\154\0\154\0\u23dc\0\u2412\0\u2448\0\154\0\u247e\0\u24b4"+
    "\0\u24ea\0\154\0\u2520\0\154\0\u2556\0\u258c\0\u25c2\0\u25f8"+
    "\0\154\0\u262e\0\u2664\0\u269a\0\u26d0\0\u2706\0\u273c\0\u2772"+
    "\0\154\0\u27a8\0\154\0\u27de\0\154\0\u2814\0\u284a\0\u2880"+
    "\0\u28b6\0\154\0\154\0\u28ec\0\u2922\0\u2958\0\154\0\u298e"+
    "\0\u29c4\0\u29fa\0\u2a30\0\u2a66\0\u2a9c\0\154\0\154\0\u2ad2"+
    "\0\u2b08\0\u2b3e\0\u2b74\0\154\0\u2baa\0\154\0\u2be0\0\u2c16"+
    "\0\u2c4c\0\u2c82\0\u2cb8\0\u2cee\0\u2d24\0\154\0\u2d5a\0\u2d90"+
    "\0\u2dc6\0\u2dfc\0\u2e32\0\u2e68\0\154\0\154\0\u2e9e\0\154"+
    "\0\154\0\u2ed4\0\u2f0a\0\u2f40";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[276];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\2\4\1\0\2\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\2\14\1\3\1\15\1\16\1\17"+
    "\1\20\1\3\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\2\3\1\30\1\31\1\3\1\32\1\33\1\34"+
    "\1\35\1\36\1\3\1\37\1\40\10\3\1\41\1\3"+
    "\1\42\1\3\1\0\2\43\1\44\1\43\1\0\1\43"+
    "\1\45\14\43\1\46\31\43\1\47\10\43\67\0\2\4"+
    "\1\0\2\4\65\0\1\50\1\0\1\51\5\0\2\52"+
    "\5\0\6\52\35\0\5\53\7\0\2\54\45\0\1\53"+
    "\16\0\2\14\50\0\5\55\7\0\2\56\45\0\1\55"+
    "\55\0\1\57\35\0\1\60\11\0\1\61\70\0\1\62"+
    "\4\0\1\63\60\0\1\64\1\0\1\65\60\0\1\66"+
    "\53\0\1\67\14\0\1\70\67\0\1\71\63\0\1\72"+
    "\60\0\1\73\72\0\1\74\4\0\1\75\61\0\1\76"+
    "\71\0\1\77\47\0\1\100\61\0\1\101\3\0\1\102"+
    "\3\0\1\103\1\104\7\0\1\105\44\0\1\106\3\0"+
    "\1\107\65\0\1\110\70\0\1\111\32\0\2\43\1\0"+
    "\1\43\1\0\1\43\1\0\14\43\1\0\42\43\54\0"+
    "\1\112\11\0\2\43\1\0\1\43\1\0\1\43\1\113"+
    "\14\43\1\0\42\43\2\50\1\0\63\50\7\0\1\114"+
    "\73\0\2\115\5\0\6\115\35\0\5\116\4\0\1\117"+
    "\2\0\2\54\45\0\1\116\2\0\5\120\4\0\1\121"+
    "\2\0\2\56\45\0\1\120\20\0\1\122\74\0\1\123"+
    "\63\0\1\124\21\0\1\125\55\0\1\126\1\0\1\127"+
    "\70\0\1\130\67\0\1\131\1\132\60\0\1\133\54\0"+
    "\1\134\74\0\1\135\66\0\1\136\55\0\1\137\100\0"+
    "\1\140\62\0\1\141\65\0\1\142\63\0\1\143\57\0"+
    "\1\144\100\0\1\145\51\0\1\146\76\0\1\147\53\0"+
    "\1\150\7\0\1\151\102\0\1\152\64\0\1\146\65\0"+
    "\1\153\40\0\1\154\111\0\1\155\57\0\1\156\56\0"+
    "\1\157\50\0\1\160\1\161\45\0\7\114\1\162\56\114"+
    "\15\0\2\163\5\0\6\163\35\0\5\116\4\0\1\117"+
    "\51\0\1\116\2\0\5\117\7\0\2\164\45\0\1\117"+
    "\2\0\5\120\4\0\1\121\51\0\1\120\2\0\5\121"+
    "\7\0\2\165\45\0\1\121\11\0\1\166\1\167\14\0"+
    "\1\170\4\0\1\171\10\0\1\172\15\0\1\173\40\0"+
    "\1\174\56\0\1\175\67\0\1\146\76\0\1\176\71\0"+
    "\1\177\64\0\1\200\66\0\1\201\45\0\1\202\102\0"+
    "\1\203\62\0\1\204\62\0\1\205\76\0\1\206\50\0"+
    "\1\207\71\0\1\210\61\0\1\211\76\0\1\212\71\0"+
    "\1\213\60\0\1\214\67\0\1\215\67\0\1\216\66\0"+
    "\1\217\50\0\1\220\65\0\1\221\73\0\1\222\65\0"+
    "\1\223\74\0\1\224\65\0\1\225\65\0\1\125\30\0"+
    "\1\226\1\227\14\0\1\230\4\0\1\231\10\0\1\232"+
    "\12\0\1\233\2\0\1\234\21\0\1\235\1\0\1\161"+
    "\45\0\7\114\1\236\56\114\15\0\2\237\5\0\6\237"+
    "\35\0\5\240\4\0\1\241\2\0\2\164\45\0\1\240"+
    "\2\0\5\242\4\0\1\243\2\0\2\165\45\0\1\242"+
    "\11\0\1\166\6\0\1\244\57\0\1\167\5\0\1\245"+
    "\72\0\1\246\71\0\1\247\102\0\1\250\37\0\1\251"+
    "\42\0\1\173\35\0\1\252\70\0\1\146\73\0\1\253"+
    "\52\0\1\254\71\0\1\255\61\0\1\256\73\0\1\257"+
    "\57\0\1\260\73\0\1\261\67\0\1\146\100\0\1\262"+
    "\46\0\1\263\67\0\1\125\107\0\1\264\41\0\1\265"+
    "\57\0\1\266\67\0\1\267\65\0\1\270\71\0\1\271"+
    "\41\0\1\226\45\0\1\272\20\0\1\227\44\0\1\273"+
    "\33\0\1\274\71\0\1\275\61\0\1\276\3\0\1\277"+
    "\6\0\1\300\5\0\1\301\77\0\1\302\64\0\1\303"+
    "\3\0\1\234\61\0\1\304\7\0\7\114\1\305\56\114"+
    "\15\0\2\306\5\0\6\306\35\0\5\240\4\0\1\241"+
    "\51\0\1\240\2\0\5\241\7\0\2\307\45\0\1\241"+
    "\2\0\5\242\4\0\1\243\51\0\1\242\2\0\5\243"+
    "\7\0\2\310\45\0\1\243\57\0\1\311\65\0\1\312"+
    "\54\0\1\313\44\0\1\314\65\0\1\315\117\0\1\316"+
    "\52\0\1\317\62\0\1\320\74\0\1\321\45\0\1\322"+
    "\66\0\1\322\75\0\1\323\77\0\1\324\54\0\1\325"+
    "\66\0\1\326\67\0\1\327\62\0\1\330\71\0\1\331"+
    "\46\0\1\332\104\0\1\302\44\0\1\333\70\0\1\334"+
    "\101\0\1\335\56\0\1\336\55\0\1\337\60\0\1\340"+
    "\63\0\2\341\5\0\6\341\35\0\5\342\3\0\1\343"+
    "\3\0\2\307\45\0\1\342\2\0\5\344\7\0\2\310"+
    "\3\0\1\345\41\0\1\344\20\0\1\346\111\0\1\347"+
    "\65\0\1\350\63\0\1\351\71\0\1\352\50\0\1\212"+
    "\102\0\1\353\60\0\1\354\63\0\1\355\57\0\1\356"+
    "\75\0\1\357\51\0\1\360\104\0\1\361\41\0\1\362"+
    "\102\0\1\363\67\0\1\364\72\0\1\365\100\0\1\366"+
    "\10\0\5\342\3\0\1\343\52\0\1\342\2\0\5\344"+
    "\14\0\1\345\41\0\1\344\57\0\1\367\54\0\1\370"+
    "\37\0\1\371\114\0\1\372\64\0\1\373\50\0\1\374"+
    "\100\0\1\375\60\0\1\376\74\0\1\377\76\0\1\272"+
    "\50\0\1\u0100\54\0\1\u0101\50\0\1\u0102\3\0\1\u0103"+
    "\65\0\1\u0104\63\0\2\u0105\37\0\1\u0106\47\0\1\u0107"+
    "\51\0\1\u0108\75\0\1\u0109\50\0\1\235\114\0\1\u010a"+
    "\36\0\1\u010b\63\0\2\u010c\64\0\2\u010c\37\0\1\u010d"+
    "\65\0\1\u010e\24\0\2\u0105\1\u010f\75\0\1\u0110\74\0"+
    "\1\u0111\60\0\1\212\100\0\1\u0112\77\0\1\273\24\0"+
    "\2\u010c\1\u0113\124\0\1\u0106\26\0\1\u0114\124\0\1\u010d"+
    "\65\0\1\303\7\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[12150];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\1\1\1\11\2\1\4\11\2\1\2\11"+
    "\21\1\2\11\1\1\2\11\3\1\42\0\1\11\32\0"+
    "\1\11\34\0\1\11\2\0\1\11\2\0\2\11\1\0"+
    "\1\11\4\0\1\11\2\0\1\11\26\0\1\11\13\0"+
    "\2\11\1\0\2\11\7\0\3\11\3\0\2\11\3\0"+
    "\1\11\3\0\1\11\1\0\1\11\4\0\1\11\7\0"+
    "\1\11\1\0\1\11\1\0\1\11\4\0\2\11\3\0"+
    "\1\11\6\0\2\11\4\0\1\11\1\0\1\11\7\0"+
    "\1\11\6\0\2\11\1\0\2\11\3\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[276];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */

private List<Token> tokens = new ArrayList<>();
private List<Token> errores = new ArrayList<>();

private boolean hayError = false;
private StringBuilder errorActual = new StringBuilder();
private int lineaErrorActual = 0;
private int columnaErrorActual = 0;

private StringBuilder bufferCadena = new StringBuilder();
private int lineaCadena = 0;
private int columnaCadena = 0;

public List<Token> getTokens(){
    return tokens;
}

public List<Token> getErrores(){
    return errores;
}

private Symbol simbolo(int type){
    return new Symbol(type, yyline, yycolumn);
}

private Symbol simbolo(int type, String value){
    return new Symbol(type, yyline, yycolumn, value);
}

private void agregarToken(TipoToken tipo){
    if(hayError){
        errorActual.append(yytext());
        lineaErrorActual = yyline + 1;
        columnaErrorActual = yycolumn + 1;
    }else{
        tokens.add(new Token(yytext(), yyline + 1, yycolumn + 1, tipo));
    }
}

private void agregarToken(String lexema, int linea, int columna, TipoToken tipo){
    tokens.add(new Token(lexema, linea, columna, tipo));
}

private void agregarError(){
    errores.add(new Token(errorActual.toString(), lineaErrorActual, columnaErrorActual, TipoToken.ERROR));
}

private void manejarEspacio(){
    if(hayError && errorActual.length() > 0){
        hayError = false;
        agregarError();
        errorActual.setLength(0);
    }
}

private Symbol agregarTextoCadena(){
    if(bufferCadena.length() > 0){
        String texto = bufferCadena.toString();
        agregarToken(texto, lineaCadena, columnaCadena, TipoToken.CADENA);
        bufferCadena.setLength(0);
        return new Symbol(sympkm.CADENA, lineaCadena - 1, columnaCadena - 1, texto);
    }
    return null;
}

private Symbol registrarYRetornar(int cupSym, TipoToken tipo){
    agregarToken(tipo);
    return simbolo(cupSym);
}

private Symbol registrarYRetornar(int cupSym, TipoToken tipo, String value){
    agregarToken(tipo);
    return simbolo(cupSym, value);
}



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LexerPKM(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws IOException if the reader could not be closed.
   */
  public final void yyclose() throws IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception IOException if any I/O-Error occurs.
   */
  @Override  public Symbol next_token() throws IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
            switch (zzLexicalState) {
            case STRING: {
              Symbol s = agregarTextoCadena();
    if (s != null) return s;
    errores.add(new Token("Cadena no cerrada", yyline + 1, yycolumn + 1, TipoToken.ERROR));
    return new Symbol(sympkm.EOF, yyline, yycolumn);
            }  // fall though
            case 277: break;
            default:
              {
                return new Symbol(sympkm.EOF, yyline, yycolumn);
              }
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { hayError = true;
    errorActual.setLength(0);
    errorActual.append(yytext());
    lineaErrorActual = yyline + 1;
    columnaErrorActual = yycolumn + 1;
    agregarError();
    hayError = false;
    errorActual.setLength(0);
            }
          // fall through
          case 57: break;
          case 2:
            { manejarEspacio();
            }
          // fall through
          case 58: break;
          case 3:
            { bufferCadena.setLength(0);
    lineaCadena = yyline + 1;
    columnaCadena = yycolumn + 1;
    yybegin(STRING);
            }
          // fall through
          case 59: break;
          case 4:
            { return registrarYRetornar(sympkm.PARENTESIS_APERTURA, TipoToken.PARENTESIS_APERTURA);
            }
          // fall through
          case 60: break;
          case 5:
            { return registrarYRetornar(sympkm.PARENTESIS_CIERRE, TipoToken.PARENTESIS_CIERRE);
            }
          // fall through
          case 61: break;
          case 6:
            { return registrarYRetornar(sympkm.COMA, TipoToken.COMA);
            }
          // fall through
          case 62: break;
          case 7:
            { return registrarYRetornar(sympkm.RESTA, TipoToken.RESTA);
            }
          // fall through
          case 63: break;
          case 8:
            { return registrarYRetornar(sympkm.DIVISION, TipoToken.DIVISION);
            }
          // fall through
          case 64: break;
          case 9:
            { return registrarYRetornar(sympkm.ENTERO, TipoToken.ENTERO, yytext());
            }
          // fall through
          case 65: break;
          case 10:
            { return registrarYRetornar(sympkm.MENOR_QUE, TipoToken.MENOR_QUE);
            }
          // fall through
          case 66: break;
          case 11:
            { return registrarYRetornar(sympkm.ASIGNACION, TipoToken.ASIGNACION);
            }
          // fall through
          case 67: break;
          case 12:
            { return registrarYRetornar(sympkm.MAYOR_QUE, TipoToken.MAYOR_QUE);
            }
          // fall through
          case 68: break;
          case 13:
            { return registrarYRetornar(sympkm.LLAVE_APERTURA, TipoToken.LLAVE_APERTURA);
            }
          // fall through
          case 69: break;
          case 14:
            { return registrarYRetornar(sympkm.LLAVE_CIERRE, TipoToken.LLAVE_CIERRE);
            }
          // fall through
          case 70: break;
          case 15:
            { if (bufferCadena.length() == 0) {
        lineaCadena = yyline + 1;
        columnaCadena = yycolumn + 1;
    }
    bufferCadena.append(yytext());
            }
          // fall through
          case 71: break;
          case 16:
            { if (bufferCadena.length() == 0) {
        lineaCadena = yyline + 1;
        columnaCadena = yycolumn + 1;
    }
    bufferCadena.append("\n");
            }
          // fall through
          case 72: break;
          case 17:
            { Symbol s = agregarTextoCadena();
    yybegin(YYINITIAL);
    if (s != null) return s;
            }
          // fall through
          case 73: break;
          case 18:
            { if (bufferCadena.length() == 0) {
        lineaCadena = yyline + 1;
        columnaCadena = yycolumn + 1;
    }
    bufferCadena.append("@");
            }
          // fall through
          case 74: break;
          case 19:
            { 
            }
          // fall through
          case 75: break;
          case 20:
            { if (bufferCadena.length() == 0) {
        lineaCadena = yyline + 1;
        columnaCadena = yycolumn + 1;
    }
    bufferCadena.append("\"");
            }
          // fall through
          case 76: break;
          case 21:
            { return registrarYRetornar(sympkm.COLOR_PREDEFINIDO, TipoToken.COLOR_PREDEFINIDO, yytext());
            }
          // fall through
          case 77: break;
          case 22:
            { return registrarYRetornar(sympkm.DROP, TipoToken.DROP);
            }
          // fall through
          case 78: break;
          case 23:
            { return registrarYRetornar(sympkm.FONT, TipoToken.FONT);
            }
          // fall through
          case 79: break;
          case 24:
            { return registrarYRetornar(sympkm.LINE, TipoToken.LINE);
            }
          // fall through
          case 80: break;
          case 25:
            { return registrarYRetornar(sympkm.FUENTE_PREDEFINIDA, TipoToken.FUENTE_PREDEFINIDA, yytext());
            }
          // fall through
          case 81: break;
          case 26:
            { return registrarYRetornar(sympkm.OPEN, TipoToken.OPEN);
            }
          // fall through
          case 82: break;
          case 27:
            { return registrarYRetornar(sympkm.SIZE, TipoToken.SIZE);
            }
          // fall through
          case 83: break;
          case 28:
            { return registrarYRetornar(sympkm.TEXT, TipoToken.TEXT);
            }
          // fall through
          case 84: break;
          case 29:
            { return registrarYRetornar(sympkm.COLOR, TipoToken.COLOR);
            }
          // fall through
          case 85: break;
          case 30:
            { return registrarYRetornar(sympkm.STYLE, TipoToken.STYLE);
            }
          // fall through
          case 86: break;
          case 31:
            { return registrarYRetornar(sympkm.TABLE, TipoToken.TABLE);
            }
          // fall through
          case 87: break;
          case 32:
            { Symbol s = agregarTextoCadena();
    if (s != null) {
        yypushback(yylength());
        return s;
    }
    return registrarYRetornar(sympkm.EMOJI_TRISTE, TipoToken.EMOJI_TRISTE);
            }
          // fall through
          case 88: break;
          case 33:
            { Symbol s = agregarTextoCadena();
    if (s != null) {
        yypushback(yylength());
        return s;
    }
    return registrarYRetornar(sympkm.EMOJI_RISA, TipoToken.EMOJI_RISA);
            }
          // fall through
          case 89: break;
          case 34:
            { Symbol s = agregarTextoCadena();
    if (s != null) {
        yypushback(yylength());
        return s;
    }
    return registrarYRetornar(sympkm.EMOJI_SERIO, TipoToken.EMOJI_SERIO);
            }
          // fall through
          case 90: break;
          case 35:
            { Symbol s = agregarTextoCadena();
    if (s != null) {
        yypushback(yylength());
        return s;
    }
    return registrarYRetornar(sympkm.EMOJI_CORAZON, TipoToken.EMOJI_CORAZON);
            }
          // fall through
          case 91: break;
          case 36:
            { return registrarYRetornar(sympkm.EMOJI_TRISTE, TipoToken.EMOJI_TRISTE);
            }
          // fall through
          case 92: break;
          case 37:
            { return registrarYRetornar(sympkm.EMOJI_RISA, TipoToken.EMOJI_RISA);
            }
          // fall through
          case 93: break;
          case 38:
            { return registrarYRetornar(sympkm.EMOJI_SERIO, TipoToken.EMOJI_SERIO);
            }
          // fall through
          case 94: break;
          case 39:
            { return registrarYRetornar(sympkm.TIPO_BORDE, TipoToken.TIPO_BORDE, yytext());
            }
          // fall through
          case 95: break;
          case 40:
            { return registrarYRetornar(sympkm.FAMILY, TipoToken.FAMILY);
            }
          // fall through
          case 96: break;
          case 41:
            { return registrarYRetornar(sympkm.SELECT, TipoToken.SELECT);
            }
          // fall through
          case 97: break;
          case 42:
            { return registrarYRetornar(sympkm.COLOR_HEXADECIMAL, TipoToken.COLOR_HEXADECIMAL, yytext());
            }
          // fall through
          case 98: break;
          case 43:
            { return registrarYRetornar(sympkm.COLOR_RGB, TipoToken.COLOR_RGB, yytext());
            }
          // fall through
          case 99: break;
          case 44:
            { return registrarYRetornar(sympkm.COLOR_HSL, TipoToken.COLOR_HSL, yytext());
            }
          // fall through
          case 100: break;
          case 45:
            { return registrarYRetornar(sympkm.CONTENT, TipoToken.CONTENT);
            }
          // fall through
          case 101: break;
          case 46:
            { return registrarYRetornar(sympkm.ELEMENT, TipoToken.ELEMENT);
            }
          // fall through
          case 102: break;
          case 47:
            { return registrarYRetornar(sympkm.SECTION, TipoToken.SECTION);
            }
          // fall through
          case 103: break;
          case 48:
            { Symbol s = agregarTextoCadena();
    if (s != null) {
        yypushback(yylength());
        return s;
    }
    return registrarYRetornar(sympkm.EMOJI_GATO, TipoToken.EMOJI_GATO);
            }
          // fall through
          case 104: break;
          case 49:
            { return registrarYRetornar(sympkm.EMOJI_GATO, TipoToken.EMOJI_GATO);
            }
          // fall through
          case 105: break;
          case 50:
            { return registrarYRetornar(sympkm.MULTIPLE, TipoToken.MULTIPLE);
            }
          // fall through
          case 106: break;
          case 51:
            { return registrarYRetornar(sympkm.VERTICAL, TipoToken.VERTICAL);
            }
          // fall through
          case 107: break;
          case 52:
            { return registrarYRetornar(sympkm.EMOJI_ESTRELLA, TipoToken.EMOJI_ESTRELLA);
            }
          // fall through
          case 108: break;
          case 53:
            { Symbol s = agregarTextoCadena();
    if (s != null) {
        yypushback(yylength());
        return s;
    }
    return registrarYRetornar(sympkm.EMOJI_ESTRELLA, TipoToken.EMOJI_ESTRELLA);
            }
          // fall through
          case 109: break;
          case 54:
            { return registrarYRetornar(sympkm.EMOJI_CORAZON, TipoToken.EMOJI_CORAZON);
            }
          // fall through
          case 110: break;
          case 55:
            { return registrarYRetornar(sympkm.BACKGROUND, TipoToken.BACKGROUND);
            }
          // fall through
          case 111: break;
          case 56:
            { return registrarYRetornar(sympkm.HORIZONTAL, TipoToken.HORIZONTAL);
            }
          // fall through
          case 112: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
