
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.example.creadorform.interprete.parser;

/** CUP generated class containing symbol constants. */
public class symform {
  /* terminals */
  public static final int HORIZONTAL = 53;
  public static final int SELECT_QUESTION = 35;
  public static final int IDENTIFICADOR = 2;
  public static final int DIVISION = 12;
  public static final int MENOR_QUE = 22;
  public static final int COLOR_PREDEFINIDO = 54;
  public static final int TABLE = 38;
  public static final int PARENTESIS_CIERRE = 16;
  public static final int CORCHETE_APERTURA = 17;
  public static final int DROP_QUESTION = 34;
  public static final int MENOR_O_IGUAL_QUE = 24;
  public static final int DIFERENTE = 26;
  public static final int ELEMENTS = 50;
  public static final int NEGACION = 29;
  public static final int DRAW = 40;
  public static final int VAR_STRING = 31;
  public static final int OPEN_QUESTION = 33;
  public static final int MAYOR_QUE = 21;
  public static final int VAR_SPECIAL = 32;
  public static final int TEXT = 39;
  public static final int DOS_PUNTOS = 65;
  public static final int WIDTH = 41;
  public static final int FUENTE_PREDEFINIDA = 55;
  public static final int TIPO_BORDE = 56;
  public static final int IGUALDAD = 25;
  public static final int STYLES = 51;
  public static final int LLAVE_CIERRE = 20;
  public static final int EMOJI_CORAZON = 72;
  public static final int COMA = 64;
  public static final int ENTERO = 3;
  public static final int MODULO = 14;
  public static final int EMOJI_TRISTE = 70;
  public static final int WHILE = 59;
  public static final int DECIMAL = 4;
  public static final int EMOJI_GATO = 74;
  public static final int MAYOR_O_IGUAL_QUE = 23;
  public static final int DO = 60;
  public static final int FOR = 61;
  public static final int COMODIN = 66;
  public static final int ORIENTATION = 45;
  public static final int ELSE = 58;
  public static final int MULTIPLE_QUESTION = 36;
  public static final int COLOR_RGB = 7;
  public static final int EMOJI_SERIO = 71;
  public static final int CORRECT = 49;
  public static final int CONTENT = 46;
  public static final int EOF = 0;
  public static final int PUNTO_Y_COMA = 68;
  public static final int PUNTO = 63;
  public static final int VERTICAL = 52;
  public static final int SUMA = 9;
  public static final int LABEL = 47;
  public static final int EMOJI_ESTRELLA = 73;
  public static final int VAR_NUMBER = 30;
  public static final int LLAVE_APERTURA = 19;
  public static final int IN = 62;
  public static final int OR = 27;
  public static final int error = 1;
  public static final int RESTA = 10;
  public static final int POINT_Y = 44;
  public static final int IF = 57;
  public static final int POINT_X = 43;
  public static final int EMOJI_RISA = 69;
  public static final int PARENTESIS_APERTURA = 15;
  public static final int MULTIPLICACION = 11;
  public static final int HEIGHT = 42;
  public static final int ASIGNACION = 67;
  public static final int CADENA = 5;
  public static final int COLOR_HSL = 8;
  public static final int OPTIONS = 48;
  public static final int AND = 28;
  public static final int CORCHETE_CIERRE = 18;
  public static final int UMINUS = 75;
  public static final int COLOR_HEXADECIMAL = 6;
  public static final int POTENCIACION = 13;
  public static final int SECTION = 37;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IDENTIFICADOR",
  "ENTERO",
  "DECIMAL",
  "CADENA",
  "COLOR_HEXADECIMAL",
  "COLOR_RGB",
  "COLOR_HSL",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "POTENCIACION",
  "MODULO",
  "PARENTESIS_APERTURA",
  "PARENTESIS_CIERRE",
  "CORCHETE_APERTURA",
  "CORCHETE_CIERRE",
  "LLAVE_APERTURA",
  "LLAVE_CIERRE",
  "MAYOR_QUE",
  "MENOR_QUE",
  "MAYOR_O_IGUAL_QUE",
  "MENOR_O_IGUAL_QUE",
  "IGUALDAD",
  "DIFERENTE",
  "OR",
  "AND",
  "NEGACION",
  "VAR_NUMBER",
  "VAR_STRING",
  "VAR_SPECIAL",
  "OPEN_QUESTION",
  "DROP_QUESTION",
  "SELECT_QUESTION",
  "MULTIPLE_QUESTION",
  "SECTION",
  "TABLE",
  "TEXT",
  "DRAW",
  "WIDTH",
  "HEIGHT",
  "POINT_X",
  "POINT_Y",
  "ORIENTATION",
  "CONTENT",
  "LABEL",
  "OPTIONS",
  "CORRECT",
  "ELEMENTS",
  "STYLES",
  "VERTICAL",
  "HORIZONTAL",
  "COLOR_PREDEFINIDO",
  "FUENTE_PREDEFINIDA",
  "TIPO_BORDE",
  "IF",
  "ELSE",
  "WHILE",
  "DO",
  "FOR",
  "IN",
  "PUNTO",
  "COMA",
  "DOS_PUNTOS",
  "COMODIN",
  "ASIGNACION",
  "PUNTO_Y_COMA",
  "EMOJI_RISA",
  "EMOJI_TRISTE",
  "EMOJI_SERIO",
  "EMOJI_CORAZON",
  "EMOJI_ESTRELLA",
  "EMOJI_GATO",
  "UMINUS"
  };
}

