
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.example.creadorform.interprete.parser;

/** CUP generated class containing symbol constants. */
public class sympkm {
  /* terminals */
  public static final int COLOR_PREDEFINIDO = 33;
  public static final int COLOR_HSL = 6;
  public static final int PARENTESIS_CIERRE = 10;
  public static final int ENTERO = 2;
  public static final int RESTA = 7;
  public static final int FUENTE_PREDEFINIDA = 34;
  public static final int EMOJI_SERIO = 40;
  public static final int FONT = 18;
  public static final int HORIZONTAL = 32;
  public static final int COLOR_HEXADECIMAL = 4;
  public static final int EMOJI_ESTRELLA = 42;
  public static final int EMOJI_CORAZON = 41;
  public static final int SELECT = 29;
  public static final int VERTICAL = 31;
  public static final int BACKGROUND = 17;
  public static final int EOF = 0;
  public static final int SIZE = 21;
  public static final int TABLE = 24;
  public static final int error = 1;
  public static final int EMOJI_GATO = 43;
  public static final int COMA = 36;
  public static final int CADENA = 3;
  public static final int LINE = 25;
  public static final int MAYOR_QUE = 13;
  public static final int EMOJI_RISA = 38;
  public static final int MULTIPLE = 30;
  public static final int ASIGNACION = 37;
  public static final int COLOR = 16;
  public static final int FAMILY = 19;
  public static final int CONTENT = 23;
  public static final int LLAVE_APERTURA = 11;
  public static final int ELEMENT = 26;
  public static final int EMOJI_TRISTE = 39;
  public static final int DROP = 28;
  public static final int OPEN = 27;
  public static final int LLAVE_CIERRE = 12;
  public static final int MENOR_QUE = 14;
  public static final int PARENTESIS_APERTURA = 9;
  public static final int TEXT = 20;
  public static final int COLOR_RGB = 5;
  public static final int SECTION = 22;
  public static final int DIVISION = 8;
  public static final int STYLE = 15;
  public static final int TIPO_BORDE = 35;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ENTERO",
  "CADENA",
  "COLOR_HEXADECIMAL",
  "COLOR_RGB",
  "COLOR_HSL",
  "RESTA",
  "DIVISION",
  "PARENTESIS_APERTURA",
  "PARENTESIS_CIERRE",
  "LLAVE_APERTURA",
  "LLAVE_CIERRE",
  "MAYOR_QUE",
  "MENOR_QUE",
  "STYLE",
  "COLOR",
  "BACKGROUND",
  "FONT",
  "FAMILY",
  "TEXT",
  "SIZE",
  "SECTION",
  "CONTENT",
  "TABLE",
  "LINE",
  "ELEMENT",
  "OPEN",
  "DROP",
  "SELECT",
  "MULTIPLE",
  "VERTICAL",
  "HORIZONTAL",
  "COLOR_PREDEFINIDO",
  "FUENTE_PREDEFINIDA",
  "TIPO_BORDE",
  "COMA",
  "ASIGNACION",
  "EMOJI_RISA",
  "EMOJI_TRISTE",
  "EMOJI_SERIO",
  "EMOJI_CORAZON",
  "EMOJI_ESTRELLA",
  "EMOJI_GATO"
  };
}

