// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: lexer3.flex

package com.example.creadorform.interprete;

import java_cup.runtime.Symbol;
import java.util.ArrayList;
import java.util.List;
import java.io.IOException;


@SuppressWarnings("fallthrough")
public class LexerForm extends Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\25\u0100\1\u0200\11\u0100\1\u0300\17\u0100\1\u0400\247\u0100"+
    "\10\u0500\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\4\22\0\1\1\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\1\0\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\3\23\1\24"+
    "\6\23\1\25\1\26\1\27\1\30\1\31\1\32\1\33"+
    "\1\34\1\35\1\36\1\37\1\40\1\41\1\42\1\43"+
    "\1\44\1\45\1\46\1\47\1\50\1\51\1\52\1\53"+
    "\1\54\1\55\1\56\1\57\1\60\1\61\1\62\1\63"+
    "\1\64\1\65\1\66\1\67\1\70\1\71\1\72\1\0"+
    "\1\73\1\74\1\75\1\76\1\77\1\100\1\101\1\102"+
    "\1\103\2\45\1\104\1\105\1\106\1\107\1\110\1\45"+
    "\1\111\1\112\1\113\1\114\1\45\1\115\1\45\1\116"+
    "\1\45\1\117\1\120\1\121\1\122\6\0\1\3\32\0"+
    "\1\123\u01df\0\1\123\177\0\13\123\35\0\2\3\5\0"+
    "\1\123\57\0\1\123\240\0\1\123\377\0\u0100\124";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1536];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\1\1\1\3\1\1\1\4\1\5"+
    "\1\1\1\6\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\1\22\25\1\26\1\27\1\30\13\25\1\31\1\1"+
    "\1\32\1\33\1\34\1\35\1\36\1\37\1\34\1\40"+
    "\1\0\1\41\6\0\1\42\1\43\1\44\1\0\2\25"+
    "\1\45\5\25\1\46\21\25\1\47\10\25\1\50\1\0"+
    "\1\51\4\0\1\52\3\0\7\25\1\53\7\25\1\54"+
    "\25\25\4\0\1\4\7\0\5\25\1\55\2\25\1\56"+
    "\1\57\7\25\1\60\4\25\1\61\13\25\23\0\11\25"+
    "\1\62\1\25\1\63\4\25\1\64\7\25\1\65\1\66"+
    "\1\67\7\0\1\70\1\71\3\0\1\72\1\73\3\0"+
    "\1\74\14\25\1\75\1\76\2\25\1\77\1\100\1\25"+
    "\1\101\1\102\6\0\1\103\1\0\1\104\1\0\1\105"+
    "\3\0\5\25\1\106\2\25\1\107\1\110\1\25\1\111"+
    "\1\25\1\112\1\113\5\0\1\114\2\0\6\25\1\115"+
    "\1\116\1\25\7\0\1\117\7\25\3\0\1\120\1\121"+
    "\1\0\1\25\1\122\4\25\2\0\4\25\1\123\1\0"+
    "\4\25\1\124\1\25\1\125\4\25\1\126\1\25\1\127";

  private static int [] zzUnpackAction() {
    int [] result = new int[389];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\125\0\252\0\377\0\u0154\0\252\0\u01a9\0\u01fe"+
    "\0\252\0\u0253\0\u02a8\0\252\0\252\0\252\0\252\0\252"+
    "\0\252\0\u02fd\0\u0352\0\252\0\252\0\u03a7\0\u03fc\0\u0451"+
    "\0\252\0\u04a6\0\u04fb\0\u0550\0\u05a5\0\u05fa\0\u064f\0\u06a4"+
    "\0\u06f9\0\u074e\0\u07a3\0\u07f8\0\u084d\0\u08a2\0\u08f7\0\u094c"+
    "\0\u09a1\0\u09f6\0\u0a4b\0\u0aa0\0\252\0\252\0\252\0\u0af5"+
    "\0\u0b4a\0\u0b9f\0\u0bf4\0\u0c49\0\u0c9e\0\u0cf3\0\u0d48\0\u0d9d"+
    "\0\u0df2\0\u0e47\0\252\0\u0e9c\0\252\0\252\0\u0ef1\0\252"+
    "\0\252\0\u0f46\0\u0f9b\0\252\0\u0ff0\0\252\0\u02a8\0\u1045"+
    "\0\u109a\0\u10ef\0\u1144\0\u1199\0\252\0\252\0\252\0\u11ee"+
    "\0\u1243\0\u1298\0\u12ed\0\u1342\0\u1397\0\u13ec\0\u1441\0\u1496"+
    "\0\u04fb\0\u14eb\0\u1540\0\u1595\0\u15ea\0\u163f\0\u1694\0\u16e9"+
    "\0\u173e\0\u1793\0\u17e8\0\u183d\0\u1892\0\u18e7\0\u193c\0\u1991"+
    "\0\u19e6\0\u1a3b\0\u04fb\0\u1a90\0\u1ae5\0\u1b3a\0\u1b8f\0\u1be4"+
    "\0\u1c39\0\u1c8e\0\u1ce3\0\252\0\u1d38\0\252\0\u1d8d\0\u1de2"+
    "\0\u1e37\0\u1e8c\0\u10ef\0\u1ee1\0\u1f36\0\u1f8b\0\u1fe0\0\u2035"+
    "\0\u208a\0\u20df\0\u2134\0\u2189\0\u21de\0\u04fb\0\u2233\0\u2288"+
    "\0\u22dd\0\u2332\0\u2387\0\u23dc\0\u2431\0\u04fb\0\u2486\0\u24db"+
    "\0\u2530\0\u2585\0\u25da\0\u262f\0\u2684\0\u26d9\0\u272e\0\u2783"+
    "\0\u27d8\0\u282d\0\u2882\0\u28d7\0\u292c\0\u2981\0\u29d6\0\u2a2b"+
    "\0\u2a80\0\u2ad5\0\u2b2a\0\u2b7f\0\u2bd4\0\u2c29\0\u2c7e\0\252"+
    "\0\u2cd3\0\u2d28\0\u2d7d\0\u2dd2\0\u2e27\0\u2e7c\0\u2ed1\0\u2f26"+
    "\0\u2f7b\0\u2fd0\0\u3025\0\u307a\0\u04fb\0\u30cf\0\u3124\0\u04fb"+
    "\0\u04fb\0\u3179\0\u31ce\0\u3223\0\u3278\0\u32cd\0\u3322\0\u3377"+
    "\0\u04fb\0\u33cc\0\u3421\0\u3476\0\u34cb\0\u04fb\0\u3520\0\u3575"+
    "\0\u35ca\0\u361f\0\u3674\0\u36c9\0\u371e\0\u3773\0\u37c8\0\u381d"+
    "\0\u3872\0\u38c7\0\u391c\0\u3971\0\u39c6\0\u3a1b\0\u3a70\0\u3ac5"+
    "\0\u3b1a\0\u3b6f\0\u3bc4\0\u3c19\0\u3c6e\0\u3cc3\0\u3d18\0\u3d6d"+
    "\0\u3dc2\0\u3e17\0\u3e6c\0\u3ec1\0\u3f16\0\u3f6b\0\u3fc0\0\u4015"+
    "\0\u406a\0\u40bf\0\u4114\0\u4169\0\u41be\0\u04fb\0\u4213\0\u04fb"+
    "\0\u4268\0\u42bd\0\u4312\0\u4367\0\u04fb\0\u43bc\0\u4411\0\u4466"+
    "\0\u44bb\0\u4510\0\u4565\0\u45ba\0\u04fb\0\252\0\252\0\u460f"+
    "\0\u4664\0\u46b9\0\u470e\0\u4763\0\u47b8\0\u480d\0\252\0\252"+
    "\0\u4862\0\u48b7\0\u490c\0\252\0\252\0\u4961\0\u49b6\0\u4a0b"+
    "\0\252\0\u4a60\0\u4ab5\0\u4b0a\0\u4b5f\0\u4bb4\0\u4c09\0\u4c5e"+
    "\0\u4cb3\0\u4d08\0\u4d5d\0\u4db2\0\u4e07\0\u04fb\0\u04fb\0\u4e5c"+
    "\0\u4eb1\0\u04fb\0\u04fb\0\u4f06\0\u04fb\0\u04fb\0\u4f5b\0\u4fb0"+
    "\0\u5005\0\u505a\0\u50af\0\u5104\0\252\0\u5159\0\252\0\u51ae"+
    "\0\252\0\u5203\0\u5258\0\u52ad\0\u5302\0\u5357\0\u53ac\0\u5401"+
    "\0\u5456\0\u04fb\0\u54ab\0\u5500\0\u04fb\0\u04fb\0\u5555\0\u04fb"+
    "\0\u55aa\0\u04fb\0\252\0\u55ff\0\u5654\0\u56a9\0\u56fe\0\u5753"+
    "\0\252\0\u57a8\0\u57fd\0\u5852\0\u58a7\0\u58fc\0\u5951\0\u59a6"+
    "\0\u59fb\0\u04fb\0\u04fb\0\u5a50\0\u5aa5\0\u5afa\0\u5b4f\0\u5ba4"+
    "\0\u5bf9\0\u5c4e\0\u5ca3\0\252\0\u5cf8\0\u5d4d\0\u5da2\0\u5df7"+
    "\0\u5e4c\0\u5ea1\0\u5ef6\0\u5f4b\0\u5fa0\0\u5ff5\0\252\0\252"+
    "\0\u604a\0\u609f\0\u04fb\0\u60f4\0\u6149\0\u619e\0\u61f3\0\u6248"+
    "\0\u629d\0\u62f2\0\u6347\0\u639c\0\u63f1\0\u04fb\0\u6446\0\u649b"+
    "\0\u64f0\0\u6545\0\u659a\0\u04fb\0\u65ef\0\u04fb\0\u6644\0\u6699"+
    "\0\u66ee\0\u6743\0\u04fb\0\u6798\0\u04fb";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[389];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\2\4\1\0\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\2\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\1\36\1\37\1\40"+
    "\1\41\1\42\1\43\2\33\1\44\1\45\1\33\1\46"+
    "\1\47\1\33\1\50\1\51\1\52\1\33\1\53\1\54"+
    "\3\33\1\55\1\3\1\56\1\57\3\33\1\60\1\61"+
    "\1\62\2\33\1\63\1\64\1\65\1\33\1\66\1\67"+
    "\1\70\1\33\1\71\2\33\1\72\1\33\1\73\1\74"+
    "\1\75\1\76\1\3\1\0\2\77\1\100\1\77\1\0"+
    "\1\77\1\101\24\77\1\102\33\77\1\103\35\77\126\0"+
    "\2\4\1\0\1\4\150\0\1\104\117\0\2\105\7\0"+
    "\6\105\31\0\6\105\24\0\2\10\1\0\122\10\12\0"+
    "\1\106\113\0\4\107\16\0\2\110\76\0\1\107\16\0"+
    "\1\111\130\0\1\112\1\0\2\23\101\0\4\113\16\0"+
    "\2\114\3\0\1\115\72\0\1\113\31\0\1\116\124\0"+
    "\1\117\162\0\1\120\61\0\2\33\7\0\32\33\4\0"+
    "\25\33\31\0\2\33\7\0\13\33\1\121\16\33\4\0"+
    "\25\33\31\0\2\33\7\0\24\33\1\122\5\33\4\0"+
    "\25\33\31\0\2\33\7\0\16\33\1\123\2\33\1\124"+
    "\10\33\4\0\25\33\31\0\2\33\7\0\13\33\1\125"+
    "\16\33\4\0\25\33\31\0\2\33\7\0\16\33\1\126"+
    "\13\33\4\0\25\33\31\0\2\33\7\0\21\33\1\127"+
    "\10\33\4\0\25\33\31\0\2\33\7\0\16\33\1\130"+
    "\13\33\4\0\25\33\31\0\2\33\7\0\5\33\1\131"+
    "\24\33\4\0\25\33\31\0\2\33\7\0\10\33\1\132"+
    "\21\33\4\0\25\33\31\0\2\33\7\0\16\33\1\133"+
    "\5\33\1\134\5\33\4\0\25\33\31\0\2\33\7\0"+
    "\17\33\1\135\12\33\4\0\25\33\31\0\2\33\7\0"+
    "\24\33\1\136\5\33\4\0\25\33\31\0\2\33\7\0"+
    "\4\33\1\137\25\33\4\0\25\33\31\0\2\33\7\0"+
    "\1\140\3\33\1\141\5\33\1\142\17\33\4\0\25\33"+
    "\31\0\2\33\7\0\1\143\3\33\1\144\25\33\4\0"+
    "\25\33\31\0\2\33\7\0\4\33\1\145\25\33\4\0"+
    "\25\33\31\0\2\33\7\0\7\33\1\146\22\33\4\0"+
    "\25\33\31\0\2\33\7\0\32\33\4\0\15\33\1\147"+
    "\7\33\31\0\2\33\7\0\32\33\4\0\17\33\1\150"+
    "\5\33\31\0\2\33\7\0\32\33\4\0\12\33\1\151"+
    "\12\33\31\0\2\33\7\0\32\33\4\0\5\33\1\152"+
    "\17\33\31\0\2\33\7\0\32\33\4\0\14\33\1\153"+
    "\10\33\31\0\2\33\7\0\32\33\4\0\1\33\1\154"+
    "\23\33\31\0\2\33\7\0\32\33\4\0\22\33\1\155"+
    "\2\33\31\0\2\33\7\0\32\33\4\0\16\33\1\156"+
    "\1\157\5\33\31\0\2\33\7\0\32\33\4\0\15\33"+
    "\1\160\7\33\31\0\2\33\7\0\32\33\4\0\16\33"+
    "\1\161\2\33\1\162\3\33\31\0\2\33\7\0\32\33"+
    "\4\0\11\33\1\163\13\33\126\0\1\164\4\0\2\77"+
    "\1\0\1\77\1\0\1\77\1\0\24\77\1\0\71\77"+
    "\66\0\1\165\36\0\2\77\1\0\1\77\1\0\1\77"+
    "\1\166\24\77\1\0\71\77\23\0\2\167\7\0\6\167"+
    "\31\0\6\167\25\0\4\170\12\0\1\171\3\0\2\110"+
    "\76\0\1\170\1\0\15\111\1\172\107\111\23\0\2\173"+
    "\101\0\4\113\16\0\2\114\76\0\1\113\2\0\4\174"+
    "\12\0\1\175\3\0\2\114\76\0\1\174\26\0\1\176"+
    "\122\0\2\33\7\0\1\177\23\33\1\200\5\33\4\0"+
    "\25\33\31\0\2\33\7\0\21\33\1\201\10\33\4\0"+
    "\25\33\31\0\2\33\7\0\23\33\1\202\1\203\5\33"+
    "\4\0\25\33\31\0\2\33\7\0\16\33\1\204\13\33"+
    "\4\0\25\33\31\0\2\33\7\0\22\33\1\205\7\33"+
    "\4\0\25\33\31\0\2\33\7\0\21\33\1\206\10\33"+
    "\4\0\25\33\31\0\2\33\7\0\4\33\1\207\25\33"+
    "\4\0\25\33\31\0\2\33\7\0\21\33\1\210\10\33"+
    "\4\0\25\33\31\0\2\33\7\0\15\33\1\211\14\33"+
    "\4\0\25\33\31\0\2\33\7\0\15\33\1\212\14\33"+
    "\4\0\25\33\31\0\2\33\7\0\13\33\1\213\16\33"+
    "\4\0\25\33\31\0\2\33\7\0\4\33\1\214\25\33"+
    "\4\0\25\33\31\0\2\33\7\0\21\33\1\215\10\33"+
    "\4\0\25\33\31\0\2\33\7\0\3\33\1\216\26\33"+
    "\4\0\25\33\31\0\2\33\7\0\15\33\1\217\14\33"+
    "\4\0\25\33\31\0\2\33\7\0\2\33\1\220\10\33"+
    "\1\221\16\33\4\0\25\33\31\0\2\33\7\0\30\33"+
    "\1\216\1\33\4\0\25\33\31\0\2\33\7\0\1\33"+
    "\1\222\30\33\4\0\25\33\31\0\2\33\7\0\27\33"+
    "\1\223\2\33\4\0\25\33\31\0\2\33\7\0\21\33"+
    "\1\224\10\33\4\0\25\33\31\0\2\33\7\0\10\33"+
    "\1\225\21\33\4\0\25\33\31\0\2\33\7\0\32\33"+
    "\4\0\14\33\1\226\2\33\1\227\5\33\31\0\2\33"+
    "\7\0\32\33\4\0\1\33\1\230\23\33\31\0\2\33"+
    "\7\0\32\33\4\0\5\33\1\231\17\33\31\0\2\33"+
    "\7\0\32\33\4\0\11\33\1\232\13\33\31\0\2\33"+
    "\7\0\32\33\4\0\2\33\1\233\22\33\31\0\2\33"+
    "\7\0\32\33\4\0\13\33\1\234\11\33\31\0\2\33"+
    "\7\0\32\33\4\0\21\33\1\235\3\33\31\0\2\33"+
    "\7\0\32\33\4\0\11\33\1\236\13\33\31\0\2\33"+
    "\7\0\32\33\4\0\11\33\1\237\13\33\31\0\2\33"+
    "\7\0\32\33\4\0\5\33\1\240\17\33\31\0\2\33"+
    "\7\0\32\33\4\0\17\33\1\241\4\33\1\242\31\0"+
    "\2\33\7\0\32\33\4\0\4\33\1\243\20\33\33\0"+
    "\1\244\1\0\1\245\120\0\2\246\7\0\6\246\31\0"+
    "\6\246\25\0\4\170\12\0\1\171\103\0\1\170\2\0"+
    "\4\171\16\0\2\247\76\0\1\171\1\0\15\111\1\172"+
    "\4\111\1\250\102\111\1\0\4\174\12\0\1\175\103\0"+
    "\1\174\2\0\4\175\16\0\2\251\76\0\1\175\14\0"+
    "\1\252\1\253\60\0\1\254\4\0\1\255\7\0\1\256"+
    "\5\0\1\257\27\0\2\33\7\0\2\33\1\260\27\33"+
    "\4\0\25\33\31\0\2\33\7\0\4\33\1\216\25\33"+
    "\4\0\25\33\31\0\2\33\7\0\22\33\1\261\7\33"+
    "\4\0\25\33\31\0\2\33\7\0\23\33\1\262\6\33"+
    "\4\0\25\33\31\0\2\33\7\0\1\33\1\263\30\33"+
    "\4\0\25\33\31\0\2\33\7\0\17\33\1\264\12\33"+
    "\4\0\25\33\31\0\2\33\7\0\4\33\1\265\25\33"+
    "\4\0\25\33\31\0\2\33\7\0\4\33\1\266\25\33"+
    "\4\0\25\33\31\0\2\33\7\0\10\33\1\267\21\33"+
    "\4\0\25\33\31\0\2\33\7\0\4\33\1\270\25\33"+
    "\4\0\25\33\31\0\2\33\7\0\16\33\1\271\13\33"+
    "\4\0\25\33\31\0\2\33\7\0\23\33\1\272\6\33"+
    "\4\0\25\33\31\0\2\33\7\0\15\33\1\273\14\33"+
    "\4\0\25\33\31\0\2\33\7\0\17\33\1\274\12\33"+
    "\4\0\25\33\31\0\2\33\7\0\22\33\1\275\7\33"+
    "\4\0\25\33\31\0\2\33\7\0\23\33\1\276\6\33"+
    "\4\0\25\33\31\0\2\33\7\0\4\33\1\277\25\33"+
    "\4\0\25\33\31\0\2\33\7\0\13\33\1\300\16\33"+
    "\4\0\25\33\31\0\2\33\7\0\23\33\1\301\6\33"+
    "\4\0\25\33\31\0\2\33\7\0\23\33\1\302\6\33"+
    "\4\0\25\33\31\0\2\33\7\0\13\33\1\303\7\33"+
    "\1\200\6\33\4\0\25\33\31\0\2\33\7\0\32\33"+
    "\4\0\21\33\1\304\3\33\31\0\2\33\7\0\32\33"+
    "\4\0\17\33\1\305\5\33\31\0\2\33\7\0\32\33"+
    "\4\0\23\33\1\306\1\33\31\0\2\33\7\0\32\33"+
    "\4\0\13\33\1\307\11\33\31\0\2\33\7\0\32\33"+
    "\4\0\7\33\1\310\15\33\31\0\2\33\7\0\32\33"+
    "\4\0\5\33\1\311\17\33\31\0\2\33\7\0\32\33"+
    "\4\0\2\33\1\312\22\33\31\0\2\33\7\0\32\33"+
    "\4\0\11\33\1\313\13\33\31\0\2\33\7\0\32\33"+
    "\4\0\5\33\1\314\17\33\31\0\2\33\7\0\32\33"+
    "\4\0\14\33\1\315\10\33\31\0\2\33\7\0\32\33"+
    "\4\0\3\33\1\316\21\33\31\0\2\33\7\0\32\33"+
    "\4\0\11\33\1\317\13\33\31\0\2\33\7\0\32\33"+
    "\4\0\12\33\1\320\12\33\31\0\2\33\7\0\32\33"+
    "\4\0\21\33\1\321\3\33\21\0\1\322\1\323\54\0"+
    "\1\324\3\0\1\325\4\0\1\326\7\0\1\327\5\0"+
    "\1\330\30\0\1\331\2\0\1\245\120\0\2\332\7\0"+
    "\6\332\31\0\6\332\25\0\4\333\12\0\1\334\3\0"+
    "\2\247\76\0\1\333\2\0\4\335\12\0\1\336\3\0"+
    "\2\251\76\0\1\335\14\0\1\252\11\0\1\337\113\0"+
    "\1\253\10\0\1\340\172\0\1\341\130\0\1\342\140\0"+
    "\1\343\36\0\1\344\72\0\1\257\27\0\2\33\7\0"+
    "\12\33\1\216\17\33\4\0\25\33\31\0\2\33\7\0"+
    "\10\33\1\345\21\33\4\0\25\33\31\0\2\33\7\0"+
    "\4\33\1\346\25\33\4\0\25\33\31\0\2\33\7\0"+
    "\13\33\1\211\16\33\4\0\25\33\31\0\2\33\7\0"+
    "\32\33\4\0\1\347\24\33\31\0\2\33\7\0\15\33"+
    "\1\216\14\33\4\0\25\33\31\0\2\33\7\0\31\33"+
    "\1\350\4\0\25\33\31\0\2\33\7\0\10\33\1\351"+
    "\21\33\4\0\25\33\31\0\2\33\7\0\32\33\4\0"+
    "\1\352\24\33\31\0\2\33\7\0\13\33\1\200\16\33"+
    "\4\0\25\33\31\0\2\33\7\0\32\33\4\0\1\353"+
    "\24\33\31\0\2\33\7\0\10\33\1\354\21\33\4\0"+
    "\25\33\31\0\2\33\7\0\2\33\1\355\27\33\4\0"+
    "\25\33\31\0\2\33\7\0\4\33\1\356\25\33\4\0"+
    "\25\33\31\0\2\33\7\0\10\33\1\357\21\33\4\0"+
    "\25\33\31\0\2\33\7\0\4\33\1\360\25\33\4\0"+
    "\25\33\31\0\2\33\7\0\32\33\4\0\5\33\1\361"+
    "\17\33\31\0\2\33\7\0\32\33\4\0\5\33\1\362"+
    "\17\33\31\0\2\33\7\0\32\33\4\0\5\33\1\363"+
    "\17\33\31\0\2\33\7\0\32\33\4\0\10\33\1\364"+
    "\14\33\31\0\2\33\7\0\32\33\4\0\12\33\1\365"+
    "\12\33\31\0\2\33\7\0\32\33\4\0\5\33\1\366"+
    "\17\33\31\0\2\33\7\0\32\33\4\0\15\33\1\367"+
    "\7\33\31\0\2\33\7\0\32\33\4\0\14\33\1\370"+
    "\10\33\31\0\2\33\7\0\32\33\4\0\21\33\1\371"+
    "\3\33\31\0\2\33\7\0\32\33\4\0\11\33\1\372"+
    "\13\33\31\0\2\33\7\0\32\33\4\0\14\33\1\373"+
    "\10\33\31\0\2\33\7\0\32\33\4\0\5\33\1\374"+
    "\17\33\31\0\2\33\7\0\32\33\4\0\10\33\1\375"+
    "\14\33\21\0\1\322\54\0\1\376\50\0\1\323\53\0"+
    "\1\377\125\0\1\u0100\126\0\1\u0101\130\0\1\u0102\120\0"+
    "\1\u0103\3\0\1\u0104\5\0\1\u0105\5\0\1\u0106\101\0"+
    "\1\u0107\27\0\1\330\74\0\1\u0108\57\0\2\u0109\7\0"+
    "\6\u0109\31\0\6\u0109\25\0\4\333\12\0\1\334\103\0"+
    "\1\333\2\0\4\334\16\0\2\u010a\76\0\1\334\2\0"+
    "\4\335\12\0\1\336\103\0\1\335\2\0\4\336\16\0"+
    "\2\u010b\76\0\1\336\71\0\1\u010c\124\0\1\u010d\147\0"+
    "\1\u010e\104\0\1\u010f\124\0\1\u0110\121\0\1\u0111\57\0"+
    "\2\33\7\0\25\33\1\u0112\4\33\4\0\25\33\31\0"+
    "\2\33\7\0\3\33\1\270\26\33\4\0\25\33\31\0"+
    "\2\33\7\0\20\33\1\u0113\11\33\4\0\25\33\31\0"+
    "\2\33\7\0\16\33\1\u0114\13\33\4\0\25\33\31\0"+
    "\2\33\7\0\17\33\1\u0115\12\33\4\0\25\33\31\0"+
    "\2\33\7\0\20\33\1\u0116\11\33\4\0\25\33\31\0"+
    "\2\33\7\0\22\33\1\u0117\7\33\4\0\25\33\31\0"+
    "\2\33\7\0\16\33\1\u0118\13\33\4\0\25\33\31\0"+
    "\2\33\7\0\23\33\1\u0119\6\33\4\0\25\33\31\0"+
    "\2\33\7\0\2\33\1\u011a\27\33\4\0\25\33\31\0"+
    "\2\33\7\0\32\33\4\0\14\33\1\u011b\10\33\31\0"+
    "\2\33\7\0\32\33\4\0\3\33\1\u011c\21\33\31\0"+
    "\2\33\7\0\32\33\4\0\14\33\1\u011d\10\33\31\0"+
    "\2\33\7\0\32\33\4\0\21\33\1\u011e\3\33\31\0"+
    "\2\33\7\0\32\33\4\0\17\33\1\u011f\5\33\31\0"+
    "\2\33\7\0\32\33\4\0\14\33\1\u0120\10\33\31\0"+
    "\2\33\7\0\32\33\4\0\21\33\1\u0121\3\33\31\0"+
    "\2\33\7\0\27\33\1\u0122\1\u0123\1\33\4\0\25\33"+
    "\31\0\2\33\7\0\32\33\4\0\1\33\1\u0124\23\33"+
    "\31\0\2\33\7\0\32\33\4\0\7\33\1\u0125\15\33"+
    "\31\0\2\33\7\0\32\33\4\0\20\33\1\u0126\4\33"+
    "\33\0\1\u0127\212\0\1\u0100\104\0\1\u0128\127\0\1\u0129"+
    "\137\0\1\u012a\116\0\1\u012b\114\0\1\u012c\54\0\2\u012d"+
    "\7\0\6\u012d\31\0\6\u012d\25\0\4\u012e\7\0\1\u012f"+
    "\6\0\2\u010a\76\0\1\u012e\2\0\4\u0130\16\0\2\u010b"+
    "\4\0\1\u0131\71\0\1\u0130\26\0\1\u0132\210\0\1\u0133"+
    "\124\0\1\u0134\36\0\2\33\7\0\4\33\1\271\25\33"+
    "\4\0\25\33\31\0\2\33\7\0\24\33\1\u0135\5\33"+
    "\4\0\25\33\31\0\2\33\7\0\15\33\1\u0136\14\33"+
    "\4\0\25\33\31\0\2\33\7\0\13\33\1\u0137\16\33"+
    "\4\0\25\33\31\0\2\33\7\0\24\33\1\u0138\5\33"+
    "\4\0\25\33\31\0\2\33\7\0\4\33\1\u0139\25\33"+
    "\4\0\25\33\31\0\2\33\7\0\15\33\1\u013a\14\33"+
    "\4\0\25\33\31\0\2\33\7\0\32\33\4\0\1\u013b"+
    "\24\33\31\0\2\33\7\0\1\u013c\31\33\4\0\25\33"+
    "\31\0\2\33\7\0\32\33\4\0\21\33\1\u013d\3\33"+
    "\31\0\2\33\7\0\32\33\4\0\21\33\1\u013e\3\33"+
    "\31\0\2\33\7\0\32\33\4\0\21\33\1\u013f\3\33"+
    "\31\0\2\33\7\0\32\33\4\0\20\33\1\u0140\4\33"+
    "\31\0\2\33\7\0\32\33\4\0\1\33\1\u0141\23\33"+
    "\31\0\2\33\7\0\32\33\4\0\12\33\1\u0142\12\33"+
    "\76\0\1\u0143\145\0\1\u0144\40\0\1\u0145\202\0\1\u0146"+
    "\125\0\1\u0147\131\0\1\u0148\14\0\4\u012e\7\0\1\u012f"+
    "\106\0\1\u012e\2\0\4\u0130\24\0\1\u0131\71\0\1\u0130"+
    "\71\0\1\u0149\147\0\1\u014a\36\0\1\u014b\122\0\2\33"+
    "\7\0\4\33\1\u014c\25\33\4\0\25\33\31\0\2\33"+
    "\7\0\23\33\1\u014d\6\33\4\0\25\33\31\0\2\33"+
    "\7\0\4\33\1\u014e\25\33\4\0\25\33\31\0\2\33"+
    "\7\0\4\33\1\u014f\25\33\4\0\25\33\31\0\2\33"+
    "\7\0\21\33\1\u0150\10\33\4\0\25\33\31\0\2\33"+
    "\7\0\20\33\1\u0151\11\33\4\0\25\33\31\0\2\33"+
    "\7\0\13\33\1\u0152\16\33\4\0\25\33\31\0\2\33"+
    "\7\0\32\33\4\0\20\33\1\u0153\4\33\31\0\2\33"+
    "\7\0\32\33\4\0\21\33\1\u0154\3\33\121\0\1\u0155"+
    "\101\0\1\376\143\0\1\u0156\114\0\1\u0157\45\0\1\u0158"+
    "\4\0\1\u0159\124\0\1\u015a\122\0\2\u015b\43\0\1\u015c"+
    "\57\0\2\33\7\0\22\33\1\u015d\7\33\4\0\25\33"+
    "\31\0\2\33\7\0\1\u015e\31\33\4\0\25\33\31\0"+
    "\2\33\7\0\32\33\4\0\1\u015f\24\33\31\0\2\33"+
    "\7\0\22\33\1\u0160\7\33\4\0\25\33\31\0\2\33"+
    "\7\0\10\33\1\u0161\21\33\4\0\25\33\31\0\2\33"+
    "\7\0\24\33\1\u0162\5\33\4\0\25\33\31\0\2\33"+
    "\7\0\32\33\4\0\11\33\1\u0163\13\33\33\0\1\331"+
    "\213\0\1\u0164\35\0\1\u0165\122\0\2\u0166\123\0\2\u0166"+
    "\43\0\1\u0167\124\0\1\u0168\57\0\2\u015b\1\u0169\122\0"+
    "\2\33\7\0\23\33\1\u016a\6\33\4\0\25\33\31\0"+
    "\2\33\7\0\13\33\1\u016b\16\33\4\0\25\33\31\0"+
    "\2\33\7\0\20\33\1\u016c\11\33\4\0\25\33\31\0"+
    "\2\33\7\0\23\33\1\u016d\6\33\4\0\25\33\31\0"+
    "\2\33\7\0\5\33\1\271\24\33\4\0\25\33\31\0"+
    "\2\33\7\0\4\33\1\u016e\25\33\4\0\25\33\31\0"+
    "\2\33\7\0\32\33\4\0\15\33\1\u016f\7\33\120\0"+
    "\1\u0170\102\0\1\377\57\0\2\u0166\1\u0171\167\0\1\u015c"+
    "\57\0\2\33\7\0\10\33\1\u0172\21\33\4\0\25\33"+
    "\31\0\2\33\7\0\24\33\1\u0173\5\33\4\0\25\33"+
    "\31\0\2\33\7\0\10\33\1\u0174\21\33\4\0\25\33"+
    "\31\0\2\33\7\0\22\33\1\u0175\7\33\4\0\25\33"+
    "\31\0\2\33\7\0\32\33\4\0\14\33\1\u0176\10\33"+
    "\33\0\1\u0177\167\0\1\u0167\57\0\2\33\7\0\16\33"+
    "\1\u0178\13\33\4\0\25\33\31\0\2\33\7\0\4\33"+
    "\1\u0179\25\33\4\0\25\33\31\0\2\33\7\0\16\33"+
    "\1\u017a\13\33\4\0\25\33\31\0\2\33\7\0\23\33"+
    "\1\u017b\6\33\4\0\25\33\76\0\1\u0107\57\0\2\33"+
    "\7\0\15\33\1\u017c\14\33\4\0\25\33\31\0\2\33"+
    "\7\0\22\33\1\u017d\7\33\4\0\25\33\31\0\2\33"+
    "\7\0\15\33\1\u017e\14\33\4\0\25\33\31\0\2\33"+
    "\7\0\10\33\1\u017f\21\33\4\0\25\33\31\0\2\33"+
    "\7\0\23\33\1\u0180\6\33\4\0\25\33\31\0\2\33"+
    "\7\0\16\33\1\u0181\13\33\4\0\25\33\31\0\2\33"+
    "\7\0\10\33\1\u0182\21\33\4\0\25\33\31\0\2\33"+
    "\7\0\15\33\1\u0183\14\33\4\0\25\33\31\0\2\33"+
    "\7\0\16\33\1\u0184\13\33\4\0\25\33\31\0\2\33"+
    "\7\0\15\33\1\u0185\14\33\4\0\25\33\6\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[26605];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\2\1\1\11\2\1\1\11\2\1\6\11"+
    "\2\1\2\11\3\1\1\11\23\1\3\11\13\1\1\11"+
    "\1\1\2\11\1\1\2\11\2\1\1\11\1\0\1\11"+
    "\6\0\3\11\1\0\43\1\1\11\1\0\1\11\4\0"+
    "\1\1\3\0\45\1\4\0\1\11\7\0\42\1\23\0"+
    "\31\1\2\11\7\0\2\11\3\0\2\11\3\0\1\11"+
    "\25\1\6\0\1\11\1\0\1\11\1\0\1\11\3\0"+
    "\16\1\1\11\5\0\1\11\2\0\11\1\7\0\1\11"+
    "\7\1\3\0\2\11\1\0\6\1\2\0\5\1\1\0"+
    "\16\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[389];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */

private List<Token> tokens = new ArrayList<>();
private List<Token> errores = new ArrayList<>();

private boolean hayError = false;
private StringBuilder errorActual = new StringBuilder();
private int lineaErrorActual = 0;
private int columnaErrorActual = 0;

private StringBuilder bufferCadena = new StringBuilder();
private int lineaCadena = 0;
private int columnaCadena = 0;

public List<Token> getTokens(){
    return tokens;
}

public List<Token> getErrores(){
    return errores;
}

private Symbol simbolo(int type){
    return new Symbol(type, yyline, yycolumn);
}

private Symbol simbolo(int type, String value){
    return new Symbol(type, yyline, yycolumn, value);
}

private void agregarToken(TipoToken tipo){
    if(hayError){
        errorActual.append(yytext());
        lineaErrorActual = yyline + 1;
        columnaErrorActual = yycolumn + 1;
    }else{
        tokens.add(new Token(yytext(), yyline + 1, yycolumn + 1, tipo));
    }
}

private void agregarToken(String lexema, int linea, int columna, TipoToken tipo){
    tokens.add(new Token(lexema, linea, columna, tipo));
}

private void agregarError(){
    errores.add(new Token(errorActual.toString(), lineaErrorActual, columnaErrorActual, TipoToken.ERROR));
}

private void manejarEspacio(){
    if(hayError && errorActual.length() > 0){
        hayError = false;
        agregarError();
        errorActual.setLength(0);
    }
}

private Symbol agregarTextoCadena(){
    if(bufferCadena.length() > 0){
        String texto = bufferCadena.toString();
        agregarToken(texto, lineaCadena, columnaCadena, TipoToken.CADENA);
        bufferCadena.setLength(0);
        return new Symbol(symform.CADENA, lineaCadena - 1, columnaCadena - 1, texto);
    }
    return null;
}

private Symbol registrarYRetornar(int cupSym, TipoToken tipo){
    agregarToken(tipo);
    return simbolo(cupSym);
}

private Symbol registrarYRetornar(int cupSym, TipoToken tipo, String value){
    agregarToken(tipo);
    return simbolo(cupSym, value);
}



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LexerForm(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws IOException if the reader could not be closed.
   */
  public final void yyclose() throws IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception IOException if any I/O-Error occurs.
   */
  @Override  public Symbol next_token() throws IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
            switch (zzLexicalState) {
            case STRING: {
              Symbol s = agregarTextoCadena();
    if (s != null) return s;
    errores.add(new Token("Cadena no cerrada", yyline + 1, yycolumn + 1, TipoToken.ERROR));
    return new Symbol(symform.EOF, yyline, yycolumn);
            }  // fall though
            case 390: break;
            default:
              {
                return new Symbol(symform.EOF, yyline, yycolumn);
              }
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { hayError = true;
    errorActual.setLength(0);
    errorActual.append(yytext());
    lineaErrorActual = yyline + 1;
    columnaErrorActual = yycolumn + 1;
    agregarError();
    hayError = false;
    errorActual.setLength(0);
            }
          // fall through
          case 88: break;
          case 2:
            { manejarEspacio();
            }
          // fall through
          case 89: break;
          case 3:
            { bufferCadena.setLength(0);
    lineaCadena = yyline + 1;
    columnaCadena = yycolumn + 1;
    yybegin(STRING);
            }
          // fall through
          case 90: break;
          case 4:
            { 
            }
          // fall through
          case 91: break;
          case 5:
            { return registrarYRetornar(symform.MODULO, TipoToken.MODULO);
            }
          // fall through
          case 92: break;
          case 6:
            { return registrarYRetornar(symform.PARENTESIS_APERTURA, TipoToken.PARENTESIS_APERTURA);
            }
          // fall through
          case 93: break;
          case 7:
            { return registrarYRetornar(symform.PARENTESIS_CIERRE, TipoToken.PARENTESIS_CIERRE);
            }
          // fall through
          case 94: break;
          case 8:
            { return registrarYRetornar(symform.MULTIPLICACION, TipoToken.MULTIPLICACION);
            }
          // fall through
          case 95: break;
          case 9:
            { return registrarYRetornar(symform.SUMA, TipoToken.SUMA);
            }
          // fall through
          case 96: break;
          case 10:
            { return registrarYRetornar(symform.COMA, TipoToken.COMA);
            }
          // fall through
          case 97: break;
          case 11:
            { return registrarYRetornar(symform.RESTA, TipoToken.RESTA);
            }
          // fall through
          case 98: break;
          case 12:
            { return registrarYRetornar(symform.PUNTO, TipoToken.PUNTO);
            }
          // fall through
          case 99: break;
          case 13:
            { return registrarYRetornar(symform.DIVISION, TipoToken.DIVISION);
            }
          // fall through
          case 100: break;
          case 14:
            { return registrarYRetornar(symform.ENTERO, TipoToken.ENTERO, yytext());
            }
          // fall through
          case 101: break;
          case 15:
            { return registrarYRetornar(symform.DOS_PUNTOS, TipoToken.DOS_PUNTOS);
            }
          // fall through
          case 102: break;
          case 16:
            { return registrarYRetornar(symform.PUNTO_Y_COMA, TipoToken.PUNTO_Y_COMA);
            }
          // fall through
          case 103: break;
          case 17:
            { return registrarYRetornar(symform.MENOR_QUE, TipoToken.MENOR_QUE);
            }
          // fall through
          case 104: break;
          case 18:
            { return registrarYRetornar(symform.ASIGNACION, TipoToken.ASIGNACION);
            }
          // fall through
          case 105: break;
          case 19:
            { return registrarYRetornar(symform.MAYOR_QUE, TipoToken.MAYOR_QUE);
            }
          // fall through
          case 106: break;
          case 20:
            { return registrarYRetornar(symform.COMODIN, TipoToken.COMODIN);
            }
          // fall through
          case 107: break;
          case 21:
            { return registrarYRetornar(symform.IDENTIFICADOR, TipoToken.IDENTIFICADOR, yytext());
            }
          // fall through
          case 108: break;
          case 22:
            { return registrarYRetornar(symform.CORCHETE_APERTURA, TipoToken.CORCHETE_APERTURA);
            }
          // fall through
          case 109: break;
          case 23:
            { return registrarYRetornar(symform.CORCHETE_CIERRE, TipoToken.CORCHETE_CIERRE);
            }
          // fall through
          case 110: break;
          case 24:
            { return registrarYRetornar(symform.POTENCIACION, TipoToken.POTENCIACION);
            }
          // fall through
          case 111: break;
          case 25:
            { return registrarYRetornar(symform.LLAVE_APERTURA, TipoToken.LLAVE_APERTURA);
            }
          // fall through
          case 112: break;
          case 26:
            { return registrarYRetornar(symform.LLAVE_CIERRE, TipoToken.LLAVE_CIERRE);
            }
          // fall through
          case 113: break;
          case 27:
            { return registrarYRetornar(symform.NEGACION, TipoToken.NEGACION);
            }
          // fall through
          case 114: break;
          case 28:
            { if (bufferCadena.length() == 0) {
        lineaCadena = yyline + 1;
        columnaCadena = yycolumn + 1;
    }
    bufferCadena.append(yytext());
            }
          // fall through
          case 115: break;
          case 29:
            { if (bufferCadena.length() == 0) {
        lineaCadena = yyline + 1;
        columnaCadena = yycolumn + 1;
    }
    bufferCadena.append("\n");
            }
          // fall through
          case 116: break;
          case 30:
            { Symbol s = agregarTextoCadena();
    yybegin(YYINITIAL);
    if (s != null) return s;
            }
          // fall through
          case 117: break;
          case 31:
            { if (bufferCadena.length() == 0) {
        lineaCadena = yyline + 1;
        columnaCadena = yycolumn + 1;
    }
    bufferCadena.append("@");
            }
          // fall through
          case 118: break;
          case 32:
            { return registrarYRetornar(symform.DIFERENTE, TipoToken.DIFERENTE);
            }
          // fall through
          case 119: break;
          case 33:
            { return registrarYRetornar(symform.AND, TipoToken.AND);
            }
          // fall through
          case 120: break;
          case 34:
            { return registrarYRetornar(symform.MENOR_O_IGUAL_QUE, TipoToken.MENOR_O_IGUAL_QUE);
            }
          // fall through
          case 121: break;
          case 35:
            { return registrarYRetornar(symform.IGUALDAD, TipoToken.IGUALDAD);
            }
          // fall through
          case 122: break;
          case 36:
            { return registrarYRetornar(symform.MAYOR_O_IGUAL_QUE, TipoToken.MAYOR_O_IGUAL_QUE);
            }
          // fall through
          case 123: break;
          case 37:
            { return registrarYRetornar(symform.DO, TipoToken.DO);
            }
          // fall through
          case 124: break;
          case 38:
            { return registrarYRetornar(symform.IF, TipoToken.IF);
            }
          // fall through
          case 125: break;
          case 39:
            { return registrarYRetornar(symform.IN, TipoToken.IN);
            }
          // fall through
          case 126: break;
          case 40:
            { return registrarYRetornar(symform.OR, TipoToken.OR);
            }
          // fall through
          case 127: break;
          case 41:
            { if (bufferCadena.length() == 0) {
        lineaCadena = yyline + 1;
        columnaCadena = yycolumn + 1;
    }
    bufferCadena.append("\"");
            }
          // fall through
          case 128: break;
          case 42:
            { return registrarYRetornar(symform.DECIMAL, TipoToken.DECIMAL, yytext());
            }
          // fall through
          case 129: break;
          case 43:
            { return registrarYRetornar(symform.FOR, TipoToken.FOR);
            }
          // fall through
          case 130: break;
          case 44:
            { return registrarYRetornar(symform.COLOR_PREDEFINIDO, TipoToken.COLOR_PREDEFINIDO, yytext());
            }
          // fall through
          case 131: break;
          case 45:
            { return registrarYRetornar(symform.ELSE, TipoToken.ELSE);
            }
          // fall through
          case 132: break;
          case 46:
            { return registrarYRetornar(symform.TIPO_BORDE, TipoToken.TIPO_BORDE, yytext());
            }
          // fall through
          case 133: break;
          case 47:
            { return registrarYRetornar(symform.FUENTE_PREDEFINIDA, TipoToken.FUENTE_PREDEFINIDA, yytext());
            }
          // fall through
          case 134: break;
          case 48:
            { return registrarYRetornar(symform.TEXT, TipoToken.TEXT);
            }
          // fall through
          case 135: break;
          case 49:
            { return registrarYRetornar(symform.DRAW, TipoToken.DRAW);
            }
          // fall through
          case 136: break;
          case 50:
            { return registrarYRetornar(symform.TABLE, TipoToken.TABLE);
            }
          // fall through
          case 137: break;
          case 51:
            { return registrarYRetornar(symform.WHILE, TipoToken.WHILE);
            }
          // fall through
          case 138: break;
          case 52:
            { return registrarYRetornar(symform.LABEL, TipoToken.LABEL);
            }
          // fall through
          case 139: break;
          case 53:
            { return registrarYRetornar(symform.WIDTH, TipoToken.WIDTH);
            }
          // fall through
          case 140: break;
          case 54:
            { Symbol s = agregarTextoCadena();
    if (s != null) {
        yypushback(yylength());
        return s;
    }
    return registrarYRetornar(symform.EMOJI_TRISTE, TipoToken.EMOJI_TRISTE);
            }
          // fall through
          case 141: break;
          case 55:
            { Symbol s = agregarTextoCadena();
    if (s != null) {
        yypushback(yylength());
        return s;
    }
    return registrarYRetornar(symform.EMOJI_RISA, TipoToken.EMOJI_RISA);
            }
          // fall through
          case 142: break;
          case 56:
            { Symbol s = agregarTextoCadena();
    if (s != null) {
        yypushback(yylength());
        return s;
    }
    return registrarYRetornar(symform.EMOJI_SERIO, TipoToken.EMOJI_SERIO);
            }
          // fall through
          case 143: break;
          case 57:
            { Symbol s = agregarTextoCadena();
    if (s != null) {
        yypushback(yylength());
        return s;
    }
    return registrarYRetornar(symform.EMOJI_CORAZON, TipoToken.EMOJI_CORAZON);
            }
          // fall through
          case 144: break;
          case 58:
            { return registrarYRetornar(symform.EMOJI_TRISTE, TipoToken.EMOJI_TRISTE);
            }
          // fall through
          case 145: break;
          case 59:
            { return registrarYRetornar(symform.EMOJI_RISA, TipoToken.EMOJI_RISA);
            }
          // fall through
          case 146: break;
          case 60:
            { return registrarYRetornar(symform.EMOJI_SERIO, TipoToken.EMOJI_SERIO);
            }
          // fall through
          case 147: break;
          case 61:
            { return registrarYRetornar(symform.HEIGHT, TipoToken.HEIGHT);
            }
          // fall through
          case 148: break;
          case 62:
            { return registrarYRetornar(symform.VAR_NUMBER, TipoToken.VAR_NUMBER);
            }
          // fall through
          case 149: break;
          case 63:
            { return registrarYRetornar(symform.POINT_X, TipoToken.POINT_X);
            }
          // fall through
          case 150: break;
          case 64:
            { return registrarYRetornar(symform.POINT_Y, TipoToken.POINT_Y);
            }
          // fall through
          case 151: break;
          case 65:
            { return registrarYRetornar(symform.VAR_STRING, TipoToken.VAR_STRING);
            }
          // fall through
          case 152: break;
          case 66:
            { return registrarYRetornar(symform.STYLES, TipoToken.STYLES);
            }
          // fall through
          case 153: break;
          case 67:
            { return registrarYRetornar(symform.COLOR_HEXADECIMAL, TipoToken.COLOR_HEXADECIMAL, yytext());
            }
          // fall through
          case 154: break;
          case 68:
            { return registrarYRetornar(symform.COLOR_RGB, TipoToken.COLOR_RGB, yytext());
            }
          // fall through
          case 155: break;
          case 69:
            { return registrarYRetornar(symform.COLOR_HSL, TipoToken.COLOR_HSL, yytext());
            }
          // fall through
          case 156: break;
          case 70:
            { return registrarYRetornar(symform.SECTION, TipoToken.SECTION);
            }
          // fall through
          case 157: break;
          case 71:
            { return registrarYRetornar(symform.CONTENT, TipoToken.CONTENT);
            }
          // fall through
          case 158: break;
          case 72:
            { return registrarYRetornar(symform.CORRECT, TipoToken.CORRECT);
            }
          // fall through
          case 159: break;
          case 73:
            { return registrarYRetornar(symform.OPTIONS, TipoToken.OPTIONS);
            }
          // fall through
          case 160: break;
          case 74:
            { return registrarYRetornar(symform.VAR_SPECIAL, TipoToken.VAR_SPECIAL);
            }
          // fall through
          case 161: break;
          case 75:
            { Symbol s = agregarTextoCadena();
    if (s != null) {
        yypushback(yylength());
        return s;
    }
    return registrarYRetornar(symform.EMOJI_GATO, TipoToken.EMOJI_GATO);
            }
          // fall through
          case 162: break;
          case 76:
            { return registrarYRetornar(symform.EMOJI_GATO, TipoToken.EMOJI_GATO);
            }
          // fall through
          case 163: break;
          case 77:
            { return registrarYRetornar(symform.VERTICAL, TipoToken.VERTICAL);
            }
          // fall through
          case 164: break;
          case 78:
            { return registrarYRetornar(symform.ELEMENTS, TipoToken.ELEMENTS);
            }
          // fall through
          case 165: break;
          case 79:
            { return registrarYRetornar(symform.EMOJI_ESTRELLA, TipoToken.EMOJI_ESTRELLA);
            }
          // fall through
          case 166: break;
          case 80:
            { Symbol s = agregarTextoCadena();
    if (s != null) {
        yypushback(yylength());
        return s;
    }
    return registrarYRetornar(symform.EMOJI_ESTRELLA, TipoToken.EMOJI_ESTRELLA);
            }
          // fall through
          case 167: break;
          case 81:
            { return registrarYRetornar(symform.EMOJI_CORAZON, TipoToken.EMOJI_CORAZON);
            }
          // fall through
          case 168: break;
          case 82:
            { return registrarYRetornar(symform.HORIZONTAL, TipoToken.HORIZONTAL);
            }
          // fall through
          case 169: break;
          case 83:
            { return registrarYRetornar(symform.ORIENTATION, TipoToken.ORIENTATION);
            }
          // fall through
          case 170: break;
          case 84:
            { return registrarYRetornar(symform.DROP_QUESTION, TipoToken.DROP_QUESTION);
            }
          // fall through
          case 171: break;
          case 85:
            { return registrarYRetornar(symform.OPEN_QUESTION, TipoToken.OPEN_QUESTION);
            }
          // fall through
          case 172: break;
          case 86:
            { return registrarYRetornar(symform.SELECT_QUESTION, TipoToken.SELECT_QUESTION);
            }
          // fall through
          case 173: break;
          case 87:
            { return registrarYRetornar(symform.MULTIPLE_QUESTION, TipoToken.MULTIPLE_QUESTION);
            }
          // fall through
          case 174: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
